### ISSUE TITLE
Error in `names<-`(read.table(quote = "", sep = "\t", textConnection(blast_out)),  :    'names' attribute [13] must be the same length as the vector [1]

### ISSUE THREAD

**Issue by leontienvdbent** [timjeske/DEUS#2]
When I try running the runBlast command, I get the following error:

```
> blast_result <- runBlast(blast_exec, blast_db, blast_ncores, sig_seq_fasta)
Blastn configuration:
D:/Werk/LUMC/MIRAS/RNA-seq/blast-2.6.0+/bin/blastn -db C:/Users/leont/Documents/R/win-library/3.5/DEUS/extdata/blastdb/DASHR_subset.fa -num_threads 2 -perc_identity 100 -dust no -soft_masking false -strand plus -task blastn-short -qcov_hsp_perc 100 -max_target_seqs 2000 -outfmt  '6 qseqid qlen sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'
Error in `names<-`(read.table(quote = "", sep = "\t", textConnection(blast_out)),  : 
  'names' attribute [13] must be the same length as the vector [1]
In addition: Warning message:
In system2(blast_exec, command, input = sig_sequences, stdout = TRUE) :
  running command '"D:/Werk/LUMC/MIRAS/RNA-seq/blast-2.6.0+/bin/blastn" -db C:/Users/leont/Documents/R/win-library/3.5/DEUS/extdata/blastdb/DASHR_subset.fa -num_threads 2 -perc_identity 100 -dust no -soft_masking false -strand plus -task blastn-short -qcov_hsp_perc 100 -max_target_seqs 2000 -outfmt  '6 qseqid qlen sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore'' had status 1
```

The same error occurs when I try to run the example data and my own data, and also when I use the latest version of BLAST+ (2.10.0+). 

Hope you can help me! Sincerely,

Leontien

**Comment by timjeske** [comment]
Dear Leontien, 

thank you for using DEUS! 

Most likely, you're issue is related to fact that you use a Windows system. 
For development and testing of DEUS, we used a Linux system. 
Thus, it might be that external system calls, like for blasting, fail on a Windows system. 

I suggest that you try to run the BLAST command as given in your error message on the command line and check which error occurs.

We would appreciated if you let us know how the problem can be solved if you find a solution. Otherwise don't hesitate to reopen the issue.

Kind regards
Tim
